server:
  port: 8080

spring:
  application:
    name: corepagos

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    configs:
      default:
        enabled: true
        maxAttempts: 3
        waitDuration: 1000
  timelimit:
    configs:
      default:
        timeoutDuration: 2000
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 500ms

endpoints:
  payment:
    path: /payments
    method: POST